accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('mypage/', views.mypage, name='mypage'),
    path('report/', views.report, name='report'),
    path('reward/', views.reward, name='reward'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from photo import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('photo.urls')),   # photo 앱이 메인
] 

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoUpdate, PhotoLike
from . import views
from .views import main, best, search_list, reward
from django.conf.urls.static import static
from django.conf import settings


app_name="photo"
urlpatterns = [
    path("photo_delete/<int:photo_id>", views.delete, name='delete'),
    path("photo_update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path('', views.main, name='main'),
    path('photo_list/', views.photo_list, name='photo_list'),
    path('best/', views.best, name='best'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name = 'like'),
    path('upload/',views.upload, name='upload'),
    path('search/', views.search_list, name='search'),
    path('today_hashtag_search/', views.today_hashtag_click, name='today_hashtag_search'),
    path('yesterday_hashtag_search/', views.yesterday_hashtag_click, name='yesterday_hashtag_search'),
    path('photo_inserts/', views.photo_insert, name='photo_insert'),
    path('reward/', views.reward, name = 'reward')
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User

# Django에서 제공하는 User 모델을 그대로 사용하며, 추가적인 필드를 덧붙이기 위해 Profile을 사용
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    reportCnt = models.IntegerField(default=0)
    rewardCnt = models.IntegerField(default=0)

accounts/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib import auth
from .models import * 
from django.contrib.auth.hashers import check_password
from photo.models import Photo
from hashtag.models import hashtag

# join, logout, mypage, report, reward 함수

def join(request):
    if request.method == "POST":
        # html 으로부터 넘어온 모든 값
        username = request.POST["username"]
        password1 = request.POST["password1"]
        password2 = request.POST["password2"]
        email = request.POST["email"]

        # 중복 ID 체크
        if User.objects.filter(username=username).exists() :
            return render(request, 'accounts/join.html', { 'is_used' : "중복된 ID 입니다."})

        # 모든 필드 미작성 시
        if (username == "") or (password1 == "") or (password2 == "") or (email == ""):
            return render(request, 'accounts/join.html', {'is_used':"모든 필드를 입력해주세요."})

        # 패스워드 불일치
        if request.POST["password1"] == request.POST["password2"]:
            user = User.objects.create_user(
                username=request.POST["username"],
                password=request.POST["password1"],
            	email=request.POST["email"] )
            profile = Profile(user=user)
            profile.save()
            auth.login(request,user)
            return redirect('/')  
        return render(request, 'accounts/join.html', {'is_used' : "패스워드가 일치하지 않습니다."})
    return render(request, 'accounts/join.html', {})


def logout(request):
    auth.logout(request)  
    return redirect('/')   

def mypage(request):
    global Photo

    # 로그인 시에만 mypage 접근 가능
    if not request.user.is_authenticated:
        print("user is not authenticated")
        return redirect('/')

    allphotos = Photo.objects.all().order_by('-like')
    photos = []

    for p in allphotos:
        if request.user == p.author :
            # print(p.image.url)
            photos.append(p)

    # 정보 수정 시
    if request.method == "POST":
        password=request.POST["password"]
        email=request.POST["email"]

        if (password != "" and email != "") or password != "" :
            request.user.set_password(password)
            request.user.save() 
            return redirect('/')  
        if email != "":
            request.user.email = email
            request.user.save()
            return render(request, 'accounts/mypage.html', {'photos' : photos})
        return render(request, 'accounts/mypage.html', {'photos' : photos})

    # if request.method == "GET":
    #     return HttpResponseRedirect('/')

    return render(request, 'accounts/mypage.html', {'photos' : photos})


# 신고받은 사진의 작성자 신고받은 횟수 +1
def report(request) :
    if request.method == "GET":
        author = request.GET['author']
        user = User.objects.get(username=author)
        user.profile.reportCnt += 1
        user.profile.save()
        return HttpResponseRedirect(request.GET['path'])

# 관리자가 날짜를 선택하면 해당 날짜 1-5등의 reward +1
def reward(request) :
    if request.method == "GET":
        date = request.GET['user_date']
        tag = ""

        for h in hashtag.objects.all():
            if (str(h.tagDate) == date):
                tag = h.tagName
                print("tag : " + tag)

        photos = Photo.objects.all().order_by('-like')
        bestPhotos =[]
        index = 0

        for p in photos :
            for h in p.hashtag['tag']:
                # print(p.hashtag['tag'])
                if (h == tag):
                    bestPhotos.append(p)
                    index += 1
                if index == 5:
                    break
            if index == 5 :
                break

        for bp in bestPhotos:
            user = User.objects.get(username=bp.author)
            print(user.profile.rewardCnt)
            user.profile.rewardCnt += 1
            print(user.profile.rewardCnt)
            user.profile.save()

        return render(request, 'accounts/mypage.html', {'bestPhotos': bestPhotos})

accounts/templates/accounts/join.html
{% load static %}
<html>
<head>
    <title> Join </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/join.css' %}">
</head>

<body style="overflow-x:hidden">
    <div class="title">
        <font id="short-title"><a href="/" class="title-text"> Photest</a></font>
        <font id="long-title">_Photo Contest </font>
    </div><br><br>

    <center>
        <h2> 회원가입 </h2>
        <div id="notice">
            본 사이트에 올리는 사진은 다른 사용자가 자유롭게 다운로드 할 수 있습니다.<br>
            이에 동의하는 사람만 회원가입 하시기 바랍니다.
        </div><br>

        <div id="join">
            <table boder="" cellspacing="10">
                <form id="join" method="POST" action="{%url 'accounts:join'%}">
                    {% csrf_token %}
                    <tr></tr><tr></tr>
                    <tr>
                        <td>ID </td>
                        <td>: <input name="username" type="text" size="20"></td>
                        <td>{{is_used}}</td>
                    </tr>

                    <tr>
                        <td>Password </td>
                        <td>: <input name="password1" type="password" size="20"></td>
                    </tr>

                    <tr>
                        <td>Comfirm Password </td>
                        <td>: <input name="password2" type="password" size="20"></td>
                    </tr>

                    <tr>
                        <td>E-mail </td>
                        <td>: <input name="email" type="E-mail" size="20"> </td>
                    </tr>
                    <tr></tr>
                    <tr>
                        <td></td>
                        <td><input type="submit" value="join" id="join_btn"></td>
                    </tr>
                </form>
            </table>
        </div><br>
    </center>
</body>
</html>

accounts/templates/accounts/login.html
{% load static %}

{% block title %}
{% endblock %}

{% block content %}
<html>

<head>
    <title> Login </title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>

<body style="overflow-x:hidden">
    <div class="title">
        <font id="short-title"><a href="/" class="title-text"> Photest</a></font>
        <font id="long-title">_Photo Contest </font>
    </div><br><br><br><br><br><br>

    <center>
        <div>
            <div id="login">
                <h2> 로그인 </h2><br>
                <form action="" method="post">
                    {% csrf_token %}
                    {{form.as_p}}
                    <br>
                    <input type="submit" value="login" class='btn btn-outline-primary' id="login_btn">
                </form>
            </div>
        </div>
    </center>
    {% endblock %}
</body>
</html>

accounts/templates/accounts/logout.html
{% block title %}
{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="'col-6">
        <div class="alert alert-primary" role="alert">
            로그아웃이 잘 되었습니다. </div>
        <a href="{% url 'accounts:login'%}" class="btn btn-outline-success">login 하기</a>
    </div>
    <div class="col"></div>

</div>
{% endblock %}

accounts/templates/accounts/mypage.html
{% load static %}
<html>
<head>
    <title>Photest</title>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/mypage.css' %}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.2/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("#div1").hide();
            $("#myinfo").click(function () {
                $("#div1").toggle();
            });
        });
        $(document).ready(function () {
            $("#myphoto").click(function () {
                $("#div2").toggle();
            });
        });
        $(document).ready(function () {
            $("#div3").hide();
            $("#report").click(function () {
                $("#div3").toggle();
            });
        });
        $(document).ready(function () {
            $("#div4").hide();
            $("#reward").click(function () {
                $("#div4").toggle();
            });
        });
        $(document).ready(function () {
            // $("#div5").hide();
            $("#adminReward").click(function () {
                $("#div5").toggle();
            });
        });
    </script>

    <style>
        .btn-like {
            position: relative;
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }
        .btn-like.active {
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/shaded_heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }
    </style>
</head>

<body style="overflow-x:hidden">
    <div class="title">
        <font id="short-title"><a href="/" class="title-text"> Photest</a></font>
        <font id="long-title">_Photo Contest </font>
    </div>
    <div id="category">
        {% if user.is_authenticated %}
        <button id="mypage_btn" class="button"><a href="{% url 'accounts:mypage' %}">MyPage</a></button>
        <button id="board_btn" class="button"><a href="http://127.0.0.1:8000/photo_list/">Board </a></button>
        <button id="best_btn" class="button"><a href="http://127.0.0.1:8000/best/"> Best </a></button>
        {% else %}
        <button id="best_btn" class="button"><a href="http://127.0.0.1:8000/best/"> Best </a></button>
        {% endif %}
    </div><br><br><br><br>

    <div class="ranking-reward">
        <font><b> Ranking Reward </b></font>
        <div class="ranking-reward-check">
            {% if user.profile.rewardCnt == 1 %}
            <img src="{% static 'image/reward_check.png' %}" />
            <img src="{% static 'image/reward.png' %}" />
            <img src="{% static 'image/reward.png' %}" />
            {% elif user.profile.rewardCnt == 2 %}
            <img src="{% static 'image/reward_check.png' %}" />
            <img src="{% static 'image/reward_check.png' %}" />
            <img src="{% static 'image/reward.png' %}" />
            {% elif user.profile.rewardCnt == 3 %}
            <img src="{% static 'image/reward_check.png' %}" />
            <img src="{% static 'image/reward_check.png' %}" />
            <img src="{% static 'image/reward_check.png' %}" />
            {% else %}
            <img src="{% static 'image/reward.png' %}" />
            <img src="{% static 'image/reward.png' %}" />
            <img src="{% static 'image/reward.png' %}" />
            {% endif %}
        </div>
    </div>

    <div class="buttons">
        <button id="myinfo" type="button"> 개인정보 수정 </button><br><br><br>
        <button id="myphoto" type="button"> 내 게시글 </button><br><br><br>
        <button id="report" type="button"> Report </button><br><br><br>
        <button id="reward" type="button"> Reward </button><br><br><br>
        {% if user.username == "hyex" %}
        <button id="adminReward" type="button"> AdminReward </button><br><br><br>
        {% endif %}
    </div><br><br>

    <form id="editInfo" action="{% url 'accounts:mypage' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div id="div1">
            <h2> 개인 정보 수정 </h2>
            <table cellspacing="10">
                <tr>
                    <td><b>User ID </b></td>
                    <td>: {{user.username}} </td>
                </tr><br>
                <tr>
                    <td><b>Password </b></td>
                    <td>: <input type="password" name="password" size="10" style="border: 3px solid gray; width:150px; height:30px;"></td>
                </tr>
                <tr></tr>
                <tr>
                    <td><b>E-mail </b></td>
                    <td>: <input type="text" name="email" size="20" placeholder="{{user.email}}" style="border: 3px solid gray; width:150px; height:30px;"></td>
                </tr>
            </table>
            <input type="submit" value="OK" id="ok_btn" />
        </div>
    </form>

    <div id="div2">
        <h2> 내 게시글 </h2>
        {% for object in photos %}
        <div id="frame">
            <form method="GET" action="{% url 'photo:delete' object.id %}">
                <button id="delete"> 삭제 </button>
            </form>
            {% block content %}
            {% endblock %}
            <div id="photos">
                <img src=" {{ object.image.url }}" class="card-img-top" width=250px height=260px />
            </div>
            <li class="list-group-item">
                {%if user in object.like.all %}
                <a href="{% url 'photo:like' object.id %}">
                    <img src="{% static 'image/shaded_heart.png' %}" class="btn-like.active" width=25px height=25px align="right"></img></a>
                {% else %}
                <a href="{% url 'photo:like' object.id %}">
                    <img src="{% static 'image/heart.png' %}" class="btn-like" width=25px height=25px align="right"></img></a>
                {%endif%}
                {% if object.like.all.count %}
                <span class="float-right">
                    {{object.like.all.count}}
                </span>
                {%endif%}
            </li>
            
            <div class="card-body">
                <p class="card-text" align="left">
                    {% if object.hashtag.tag.0 %}
                    # {{ object.hashtag.tag.0 }}
                    {% endif %}
                    {% if object.hashtag.tag.1 %}
                    # {{object.hashtag.tag.1}}
                    {% endif %}
                    {% if object.hashtag.tag.2 %}
                    # {{object.hashtag.tag.2}}
                    {% endif %}
                </p>
            </div>
        </div>
        {% endfor %}
    </div>

    <div id="div3">
        <h2> Report 당한 횟수 : {{user.profile.reportCnt}} 번</h2>
    </div>

    <div id="div4">
        <h2> Reward 받은 횟수 : {{user.profile.rewardCnt}} 번</h2><br><br>
        <form id="reward" method="get" action="{% url 'photo:reward' %}">
            <table boder="" cellspacing="10">
                <tr>
                    <td><b>지정할 해시태그 </b></td>
                    <td> : <font weight="bold"> # </font><input type="text" name="user_hashtag" size="15" style="border: 3px solid gray; width:150px; height:30px;"></td>
                </tr>
                <tr>
                    <td> <b>지정할 날짜 </b></td>
                    <td> : <input type="date" name="user_date" style="border: 3px solid gray; width:150px; height:30px;"></td>
                </tr>
                {%if user.profile.rewardCnt == 3 %}
                <tr>
                    <td></td>
                    <td><input type="submit" value="OK" id="rconfirm" /></td>
                </tr>
                {% endif %}
            </table>
        </form>
    </div>

    {% if user.username == "hyex" %}
    <div id="div5">
        <form id="rewardCnt" method="get" action="{% url 'accounts:reward' %}">
            <input type="date" name="user_date" style="border: 3px solid gray; width:150px; height:30px;">
            <input type="submit" value="OK" id="ok_confirm" />
            <input type="hidden" name="path" value="{{request.path}}" />
        </form>
        {% endif %}
        {% for object in bestPhotos %}
        <b>{{ object.author }}</b><br>
        {% endfor %}
    </div>
</body>
</html>