accounts/urls.py
from django.urls import path
from django.contrib.auth.views import LoginView, LogoutView
from . import views

app_name = "accounts"

urlpatterns = [
    path('login/', LoginView.as_view(template_name = 'accounts/login.html'), name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('mypage/', views.mypage, name='mypage'),
    path('report/', views.report, name='report'),
    path('reward/', views.reward, name='reward'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from photo import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('photo.urls')),   # photo 앱이 메인
] 

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/urls.py
from django.urls import path
from .views import PhotoList, PhotoUpdate, PhotoLike
from . import views
from .views import main, best, search_list, reward
from django.conf.urls.static import static
from django.conf import settings


app_name="photo"
urlpatterns = [
    path("photo_delete/<int:photo_id>", views.delete, name='delete'),
    path("photo_update/<int:pk>/", PhotoUpdate.as_view(), name='update'),
    path('', views.main, name='main'),
    path('photo_list/', views.photo_list, name='photo_list'),
    path('best/', views.best, name='best'),
    path("like/<int:photo_id>/", PhotoLike.as_view(), name = 'like'),
    path('upload/',views.upload, name='upload'),
    path('search/', views.search_list, name='search'),
    path('today_hashtag_search/', views.today_hashtag_click, name='today_hashtag_search'),
    path('yesterday_hashtag_search/', views.yesterday_hashtag_click, name='yesterday_hashtag_search'),
    path('photo_inserts/', views.photo_insert, name='photo_insert'),
    path('reward/', views.reward, name = 'reward')
]

urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

photo/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
import jsonfield

class Photo(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='user')
    image = models.ImageField(upload_to= 'timeline_photo/%Y/%m/%d')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    hashtag = jsonfield.JSONField(blank = True, null = True)
    like = models.ManyToManyField(User, related_name='like_post', blank=True)
    likecnt = models.IntegerField(default=0)
    
    def __str__(self): # admin 사이트 화면 표시 구현
        return "image : "+str(self.image.name)
        # return "image : "+str(self.likecnt)

    class Meta: # ordering 정렬
        # ordering = ['-likecnt']
        ordering = ['-created']

    def get_absolute_url(self):
        return reverse('photo:detail', args=[self.id])

photo/views.py
from django.views.generic.list import ListView
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.views.generic.detail import DetailView
from django.shortcuts import render, get_object_or_404
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone
from .models import Photo
from .models import User
from accounts.models import Profile
from hashtag.models import hashtag
from django.http import HttpResponseRedirect
from django.contrib import messages
from datetime import datetime
from datetime import date, timedelta
from django.db import connection
import json
from urllib.parse import urlparse
from django.core.files import File
import urllib.request
from django.shortcuts import render
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from django.template import RequestContext
from django.utils.dateparse import parse_date
from django.views.generic.base import View
from django.http import HttpResponseForbidden
from urllib.parse import urlparse


def main(request):
    print('main')
    global hashtag
    global Photo
    hashtags = hashtag.objects.all()

    #------------------------- 오늘의 해시태그 & 어제의 해시태그 처리 ----------------------------
    todaytag = ""
    todayDate = str(date.today())

    yesterdaytag = ""
    today = date.today()
    yesterday = str(date.today() - timedelta(1))

    for h in hashtag.objects.all() :
        if(str(h.tagDate) == todayDate) : 
            todaytag = h.tagName
        
        if(str(h.tagDate) == yesterday) :
            yesterdaytag = h.tagName
            
    # ------------------------- 어제의 Best 5 ----------------------------
    Photos = Photo.objects.all().order_by('-like')
    BestPhotos = list()

    index = 0
    for p in Photos :
        for t in p.hashtag['tag'] :
            if(t == yesterdaytag) : 
                BestPhotos.append(p)
                index += 1
                break
            if(index == 5) : break

    print('BestPhotos in main size : ', len(BestPhotos))
    for p in BestPhotos :
        print(p.image)

    return render(request, 'photo/main.html', context={'todaytag' : todaytag, 'yesterdaytag' : yesterdaytag, 'BestPhotos' : BestPhotos})
    
def best(request):
    yesterday = date.today() - timedelta(1)
    
    days = [yesterday]
    tags = []
    bestPhotos =[]
    temp = 0
    for i in range(1, 7):
        temp = yesterday - timedelta(i)
        days.append(temp)

    for i in range(0, 7):
        for h in hashtag.objects.all():
            if (h.tagDate == days[i]):
                tags.append(h.tagName)

    photos = Photo.objects.all().order_by('-likecnt')

    index = -1
    for t in tags :
        index = 0
        for p in photos :
            print(p.image.name)
            for h in p.hashtag['tag'] :
                if t == h :
                    print("best :" + p.image.name)
                    bestPhotos.append(p)
                    index += 1
                    break
            if index == 5 :
                break

    return render(request, 'photo/best.html', context={'days': days, 'tags': tags, 'bestPhotos': bestPhotos})

def upload(request):
    return render(request, 'photo/upload.html', {})

def search_list(request):
    print('search list')
    Photos = Photo.objects.all()
    PhotosWithHashtag = list()
    search = request.GET.get('search', '') # GET request의 인자중에 q 값이 있으면 가져오고, 없으면 빈 문자열 넣기
    
    for p in Photos :
        for t in p.hashtag['tag'] :
            if(t == search) : 
                PhotosWithHashtag.append(p)

    # print(PhotosWithHashtag)
    # print(search)

    return render(request, 'photo/search_list.html', {
        'PhotosWithHashtag' : PhotosWithHashtag,
        'search' : search
    })


def today_hashtag_click(request) :
    print('today hashtag click')
    Photos = Photo.objects.all()
    PhotosWithHashtag = list()

    global hashtag
    hashtags = hashtag.objects.all()
    todaytag = ""
    todayDate = str(date.today())

    for h in hashtag.objects.all() :
        if(str(h.tagDate) == todayDate) : 
            todaytag = h.tagName

    print(todaytag)
    
    for p in Photos :
        for t in p.hashtag['tag'] :
            if(t == todaytag) :
                PhotosWithHashtag.append(p)
    
    return render(request, 'photo/search_list.html', {
        'PhotosWithHashtag' : PhotosWithHashtag,
        'search' : todaytag
    })

def yesterday_hashtag_click(request) :
    print('yesterday hashtag click')
    Photos = Photo.objects.all()
    PhotosWithHashtag = list()

    yesterdaytag = ""
    today = date.today()
    yesterday = str(date.today() - timedelta(1))

    for h in hashtag.objects.all() :        
        if(str(h.tagDate) == yesterday) :
            yesterdaytag = h.tagName
    
    print(yesterdaytag)
    
    for p in Photos :
        for t in p.hashtag['tag'] :
            if(t == yesterdaytag) :
                PhotosWithHashtag.append(p)
    

    return render(request, 'photo/search_list.html', {
        'PhotosWithHashtag' : PhotosWithHashtag,
        'search' : yesterdaytag
    })

def board_search(self, request, *args, **kwargs) :
    print('board search')
    Photos = Photo.objects.all()
    PhotosWithHashtag = list()

    search = request.GET.get('search', '')
    for p in Photos :
        for t in p.hashtag['tag'] :
            if(t == search) :
                PhotosWithHashtag.append(p)
    
    return render(request, 'photo/search_list.html', {
        'PhotosWithHashtag' : PhotosWithHashtag,
        'search' : search
    })

def photo_list(request) :
    print('photo list')
    Photos = Photo.objects.all()
    PhotosWithHashtag = list()

    global hashtag
    hashtags = hashtag.objects.all()
    todaytag = ""
    todayDate = str(date.today())

    for h in hashtag.objects.all() :
        if(str(h.tagDate) == todayDate) : 
            todaytag = h.tagName

    print(todaytag)
    
    for p in Photos :
        PhotosWithHashtag.append(p)
    
    return render(request, 'photo/photo_list.html', {
        'PhotosWithHashtag' : PhotosWithHashtag,
        'todaytag' : todaytag
    })

def photo_insert(request) :
    print('photo create')
    username = request.user
    Users = User.objects.all()
    authorid = ""

    for u in Users :
        if(str(u.username) == str(username)) :
            authorid = u
            
    image = request.FILES['image']
    hashtag1 = request.POST.get('hashtag1', '')
    hashtag2 = request.POST.get('hashtag2', '')
    hashtag3 = request.POST.get('hashtag3', '')

    hashtag = {
        'tag' : []
    }

    if(hashtag1 != "") :
        hashtag['tag'].append(hashtag1)
    if(hashtag2 != "") :
        hashtag['tag'].append(hashtag2)
    if(hashtag3 != "") :
        hashtag['tag'].append(hashtag3)

    print(hashtag['tag'])

    data = Photo.objects.create(author = authorid, image = image, hashtag = hashtag)
    return HttpResponseRedirect('/photo_list/')



def reward(request) :
    # 사용자가 지정한 날짜, 해시태그 이름, 해시태그 테이블에 추가 혹은 수정
   
    global hashtag
    hashtags = hashtag.objects.all()
    requestdate = request.GET.get('user_date', '')
    convertdate = datetime.strptime(requestdate, "%Y-%m-%d")
  
    requesttag = request.GET.get('user_hashtag','')
    username = request.user
    Users = User.objects.all()
    authorid = ""

    for u in Users :
        if(str(u.username) == str(username)) :
            authorid = u.id

    set_instance = Profile.objects.get(user = authorid)
    set_instance.rewardCnt = 0
    set_instance.save()    

    index =0
    temp =""
    length = len(hashtags)
    for h in hashtags :
        #있으면 update
        if(h.tagName == requesttag) :
            temp = convertdate.date()
            h.tagDate = temp
            
            update_instance = hashtag.objects.get(tagName = requesttag)
            update_instance.tagDate = temp
            update_instance.save()
            break
        index += 1
    
    #없으면 insert
    if(index == length) :
        insert_instance = hashtag(tagName = requesttag, tagDate = convertdate.date())
        insert_instance.save()

    return render(request, 'accounts/mypage.html', { 'Message' : 'reward complete' })


class PhotoList(ListView) :
    print('PhotoList')
    model = Photo
    emplate_name_suffix='_list'

    def search(request) :
        print(' def fun inside')
        return render(request, 'photo/photo_list.html', {"PhotosWithHashtag" : PhotosWithHashtag})


class PhotoUpdate(UpdateView):
    model = Photo
    fields = ['author','text', 'image']
    template_name_suffix = '_update'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '수정할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoUpdate, self).dispatch(request, *args, **kwargs)

def delete(request, photo_id):
    photo = Photo.objects.get(id=photo_id)
    print(photo.author)
    photo.delete()

    allphotos = Photo.objects.all().order_by('-like')
    photos = []

    for p in allphotos:
        if request.user == p.author:
            # print(p.image.url)
            photos.append(p)

    return HttpResponseRedirect('/accounts/mypage')


class PhotoDelete(DeleteView):
    print("delete")
    model = Photo
    template_name_suffix = '_delete'
    success_url = '/'

    def dispatch(self, request, *args, **kwargs):
        object = self.get_object()
        if object.author != request.user:
            messages.warning(request, '삭제할 권한이 없습니다.')
            return HttpResponseRedirect('/')
        else:
            return super(PhotoDelete, self).dispatch(request, *args, **kwargs)

class PhotoLike(ListView):
    model = Photo
    template_name_suffix='_like'

    def get(self, request, *args, **kwargs):
        if not request.user.is_authenticated:  # 로그인확인
            messages.warning(request, '로그인을 먼저하세요')

photo/templates/photo/main.html
{% load static %}
<html>
<head>
    <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4/jquery.min.js"></script>
    <script type="text/javascript" src="http://code.jquery.com/jquery-1.12.4.min.js"></script>
</head>

<body style="overflow-x:hidden">
    <script type="text/javascript">
        function scroll_follow(id) {
            $(window).scroll(function ()  //스크롤이 움직일때마다 이벤트를 발생시키고   
            {
                var position = $(window).scrollTop(); // 현재 스크롤바의 위치값을 반환합니다.       
                $(id).stop().animate({ top: position + "px" }, 1); //해당 오브젝트 위치값 재설정    
            });
        }
        scroll_follow("#scroll");
        //스크롤이 생기도록 <br> 을 여러개 넣은 부분..
        $(document).ready(function () { for (var i = 0; i < 200; i++) { $('#brr').html($('#brr').html() + "<br>" + i); } });
    </script>

    <div id="scroll" style="position:absolute;left:0;">
        <div class="menu-bar">
            <font class="short-title"><a href="/" class="title-text"> Photest</a></font>
            <font id="long-title">_Photo Contest </font>

            {% if user.is_authenticated %}
            <button id="board_btn" class="button"><a href="http://127.0.0.1:8000/photo_list/">
                    <font color="gray"> Board </font>
                </a></button>
            <button id="best_btn" class="button"><a href="http://127.0.0.1:8000/best/">
                    <font color="gray"> Best </font>
                </a></button>
            <button id="mypage_btn" class="button"><a href="{%url 'accounts:mypage'%}">
                    <font color="gray">MyPage</font>
                </a></button>
            {% endif %}
        </div>
    </div>

    <div id="title">
        <font id="short"> Photest</font>
    </div>
    <div id="intro">
        <font id="main_intro"> Photest는 타인과의 연결없이 즐기는<Br> 당신만을 위한 공간입니다.</font><br><br><br>
        <font id="sub_intro">매일 달라지는 해시태그에 따라 이 공간의 주인공이 되어보세요. </font>
    </div>
    <div id="login-join">
        {% if user.is_authenticated %}
        <font id="userid" style="color:gray">"</font>
        <font id="userid" style="color:#edb928">{{user.username}}</font>
        <font id="userid" style="color:gray">님 환영합니다." </font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="logout"><a href="{% url 'accounts:logout'%}">Logout </a></button>
        {% else %}
        <button id="login"><a href="http://127.0.0.1:8000/accounts/login/" style="color:gray"> Login </a></button>
        &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
        <button id="join"><a href="http://127.0.0.1:8000/accounts/join/" style="color:white"> Join </a></button>
        {% endif %}
    </div>

    <div id="today-hashtag">
        <font id="today-container">today's hastag </font> &nbsp;&nbsp;
        {% if user.is_authenticated %}
        <font id="today_hashtag"><a href="http://127.0.0.1:8000/today_hashtag_search/" style="color:#edb928">#
                {{todaytag}} </a></font>
        {% else %}
        <font id="today_hashtag2"><a href="/" style="color:#edb928"> # {{todaytag}} </a></font>
        {% endif %}
    </div>

    {% if user.is_authenticated %}
    <font id="board" style="color:gray">오늘의 사진 올리러 가기</font>
    <a href="http://127.0.0.1:8000/upload/"><img src="{% static 'image/next.png' %}" id="board_img"></a>
    <form id="search" action="{% url 'photo:search' %}" method="get">
        {% endif %}
        <div id="dsearch">
            <input type="text" id="isearch" name="search" placeholder="# Hashtag를 입력하세요" />
            <input type="submit" value="search" id="bsearch" />
        </div>
    </form>

    <div id="yesterday-hashtag">
        <font id="yesterday-container">yesterday's hastag </font> &nbsp;&nbsp;
        {% if user.is_authenticated %}
        <font id="yesterday_hashtag" style="color:#edb928"><a href="http://127.0.0.1:8000/yesterday_hashtag_search/"
                style="color:#edb928">
                # {{yesterdaytag}}</a></font>
        {% else %}
        <font id="yesterday_hashtag" style="color:#edb928"><a href="/" style="color:#edb928"> # {{yesterdaytag}} </a>
        </font>
        {% endif %}
    </div>
    <img src="{% static 'image/crown.png' %}" id="first-rank" />
    <div id="rank">
        <h1> 1등 : {{BestPhotos.0.author}} </h1>
    </div>

    <div id="image">
        <div class="yesterday-first">
            <img src="{{ BestPhotos.0.image.url }}" />
        </div>

        <div class="yesterday-else">
            <div class="yesterday-else1">
                <img src="{{ BestPhotos.1.image.url }}" />
            </div>
            <div class="yesterday-else2">
                <img src="{{ BestPhotos.2.image.url }}" />
            </div>
            <div class="yesterday-else3">
                <img src="{{ BestPhotos.3.image.url }}" />
            </div>
            <div class="yesterday-else4">
                <img src="{{ BestPhotos.4.image.url }}" />
            </div>
        </div>
    </div>

    <div id="banner">
        <br><br>
        <center>
            <img src="{% static 'image/sea.png' %}" id="sea_logo">
            <p class="copyright">Copyright ©2019 SEA <br>
                https://github.com/DGU-SEA/Photest </p>
        </center>
    </div>
</body>
</html>

photo/templates/photo/newPhoto.html
{% extends 'photo/photo_create.html' %}
{% block content %}
<style type="text/css">
    #frame{
        position : relative;
        padding : 10px;
        width : 250px;
        top : 180px;
        height : 330px;
        border : 1px solid gray;
        float : left;
        margin-right : 50px;
    }

    #photos {
        width : 250px;
        height : 260px;
        position : relative;
        border : 1px solid gray;
    }
</style>
<div id = "frame" >
        <div id = "photos">
            <img src=" {{ Photo.image.url }}" class="card-img-top" alt="..." z-index="-1" width=250px height=260px/>
        </div>
        <!-- <img src=" {{ object.image.url }}" class="card-img-top" alt="..." align = "right" z-index="-1"/>  -->
        <!-- <img src=" {{ Photo.image.url }}" class="card-img-top" alt="..." align = "right" z-index="-1"/> -->
                <img src="{% static 'image/heart.png' %}" width=250px height=260px class="card-img-top" alt="...">
        </div>
        <img id="heart" src="{% static 'image/heart.png' %}" width=30px height=30px align = "right"/>
        {% block content %}
        {% endblock %}
    </div>
{% endblock %}

photo/templates/photo/photo_detail.html
{%extends 'photo/detail_view.html'%}
{% block title %}
{% endblock %}

{% load static %}
{%block content%}
<div class="row">
    <div class="col"></div>
    <div class="col-12 col-xl-4 col-md-4">
        <div class="card" style="width: 30rem;">
            <img src="{{object.image.url}}" class="card-img-top" alt="...">
            <div class="card-body">
                <h5 class="card-title">{{object.author}}</h5>
                <p class="card-text"> {{object.text}}</p>
            </div>
            <ul class="list-group list-group-flush">
                {{object.like.all.count}}
                <a href="{% url 'photo:like' object.id %}"
                    class="btn-like {%if user in object.like.all %} active {%endif%}"></a>
                {% endif %}
                <li class="list-group-item">생성일 : {{object.created}}</li>
                <li class="list-group-item">생성일 : {{object.updated}}</li>
            </ul>
        </div>
        {%endfor%}
    </div>
    <div class="col"></div>
</div>
{%endfor%}

photo/templates/photo/photo_list.html
{% load static %}
<html>

<head>
    <link rel="stylesheet" href="{% static 'css/photo_list.css' %}">
    <title> Photest </title>
    <meta charset="utf-8">
    <script type="text/javascript">
        function remove_div(obj) {
            document.getElementById('frame').removeChild(obj.parentNode);
        }
    </script>

    <style>
        .btn-like {
            position: relative;
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }

        .btn-like.active {
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/shaded_heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }
    </style>

</head>

<body style="overflow-x:hidden">
    <div class="title">
        <font id="short-title"><a href="/" class="title-text"> Photest</a></font>
        <font id="long-title">_Photo Contest </font>
    </div>
    <div id="category">
        {% if user.is_authenticated %}
        <button id="mypage_btn" class="button"><a href="{%url 'accounts:mypage'%}">MyPage</a></button>
        <button id="board_btn" class="button"><a href="http://127.0.0.1:8000/photo_list/">Board </a></button>
        <button id="best_btn" class="button"><a href="http://127.0.0.1:8000/best/"> Best </a></button>
        {% endif %}
    </div>

    <div id="today-hashtag">
        <font id="today-container">today's hastag </font> &nbsp;&nbsp;
        <font id="today_hashtag"><a href="http://127.0.0.1:8000/today_hashtag_search/" style="color:#edb928">#
                {{todaytag}} </a></font>
    </div>

    <br><br>

    <form id="search" action="{% url 'photo:search' %}" method="get">
        <div id="dsearch">
            <input type="text" id="isearch" name="search" value="{{search}}" placeholder="# Hashtag를 입력하세요" />
            <input type="submit" value="search" id="bsearch" />
        </div>
    </form>
    <div id="board">
        <div class="add">
            <button class="button">
                <p class="plus">
                    <!-- <font size=80px> -->
                        <a href="http://127.0.0.1:8000/upload/"> + </a>
                    <!-- </font> -->
                </p>
            </button>
        </div>
        {% for object in PhotosWithHashtag %}
        <div id="frame-frame">
            <div id="frame">
                <form method="GET" action="{% url 'accounts:report' %}">
                    <input type="hidden" name="path" value="{{request.path}}" />
                    <input type="hidden" name="author" value="{{object.author}}" />
                    <button id="report">신고</button>
                </form>

                <div id="photos">
                    <img src=" {{ object.image.url }}" class="card-img-top" alt="..." width=250px height=260px />
                </div>

                <a href="{{object.image.url}}" download="photo.jpg">
                    <img id="download" src="{% static 'image/download.png' %}" width=25px height=25px
                        align="right"></img>

                    <li class="list-group-item">
                        {%if user in object.like.all %}
                        <a href="{% url 'photo:like' object.id %}">
                            <img src="{% static 'image/shaded_heart.png' %}" class="btn-like.active" width=25px
                                height=25px align="right"></img></a>
                        {% else %}
                        <a href="{% url 'photo:like' object.id %}">
                            <img src="{% static 'image/heart.png' %}" class="btn-like" width=25px height=25px
                                align="right"></img></a>
                        {%endif%}
                        {% if object.like.all.count %}
                        <span class="float-right">
                            {{object.like.all.count}}
                        </span>
                        {%endif%}
                    </li>
                    
                    <div class="card-header" align="left">
                        &nbsp;&nbsp;{{ object.author }} >
                    </div>

                    <div class="card-body">
                        <p class="card-text" align="left">
                            {% if object.hashtag.tag.0 %}
                            &nbsp; # {{ object.hashtag.tag.0 }}
                            {% endif %}
                            {% if object.hashtag.tag.1 %}
                            # {{object.hashtag.tag.1}}
                            {% endif %}
                            {% if object.hashtag.tag.2 %}
                            # {{object.hashtag.tag.2}}
                            {% endif %}
                        </p>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</body>

</html>

photo/templates/photo/search_list.html
{% load static %}
<html>
<head>
    <link rel="stylesheet" href="{% static 'css/searchlist.css' %}">
    <title> Photest </title>
    <meta charset="utf-8">
    <script type="text/javascript">
        function remove_div(obj) {
            document.getElementById('frame').removeChild(obj.parentNode);
        }
    </script>

    <style>
        .btn-like {
            position: relative;
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }

        .btn-like.active {
            display: inline-block;
            width: 25px;
            height: 25px;
            background: url("/static/images/shaded_heart.png");
            text-indent: -9999px;
            overflow: hidden;
            border: none;
        }
    </style>
</head>

<body style="overflow-x:hidden">
    <div class="title">
        <font id="short-title"><a href="/" class="title-text"> Photest</a></font>
        <font id="long-title">_Photo Contest </font>
    </div>
    <div id="category">
        {% if user.is_authenticated %}
        <button id="mypage_btn" class="button"><a href="{%url 'accounts:mypage'%}">MyPage</a></button>
        <button id="board_btn" class="button"><a href="http://127.0.0.1:8000/photo_list/">Board </a></button>
        <button id="best_btn" class="button"><a href="http://127.0.0.1:8000/best/"> Best </a></button>
        {% endif %}
    </div><br><br><br>

    <div class="today-hashtag">
        <h1> # {{search}} </h1>
    </div><br><br>

    <div>
        <div>
            <div>
                <form id="search" action="{% url 'photo:search' %}" method="get">
                    <div id="dsearch">
                        <input type="text" id="isearch" name="search" placeholder="# Hashtag를 입력하세요" />
                        <input type="submit" value="search" id="bsearch" />
                    </div>
                </form>
            </div>
        </div>
    </div>
    <div id="board">
        {% for object in PhotosWithHashtag %}
        <div id="frame_frame">
            <div id="frame">
                <form method="GET" action="{% url 'accounts:report' %}">
                    <input type="hidden" name="path" value="{{request.path}}" />
                    <input type="hidden" name="author" value="{{object.author}}" />
                    <button id="report">신고</button>
                </form>

                <div id="photos">
                    <img src=" {{ object.image.url }}" class="card-img-top" alt="..." width=250px height=260px />
                </div>

                <a href="{{object.image.url}}" download="photo.jpg">
                    <img id="download" src="{% static 'image/download.png' %}" width=25px height=25px align="right"></img>

                <li class="list-group-item">
                    {%if user in object.like.all %}
                    <a href="{% url 'photo:like' object.id %}">
                        <img src="{% static 'image/shaded_heart.png' %}" class="btn-like.active" width=25px
                            height=25px align="right"></img></a>
                    {% else %}
                    <a href="{% url 'photo:like' object.id %}">
                        <img src="{% static 'image/heart.png' %}" class="btn-like" width=25px height=25px
                            align="right"></img></a>
                    {%endif%}
                    {% if object.like.all.count %}
                    <span class="float-right">
                        {{object.like.all.count}}
                    </span>
                    {%endif%}
                </li>
                    
                    <div class="card-header" align="left">
                        &nbsp;&nbsp;{{ object.author }} >
                    </div>

                    <div class="card-body">
                        <p class="card-text" align="left">
                            {% if object.hashtag.tag.0 %}
                            &nbsp;&nbsp;# {{ object.hashtag.tag.0 }}
                            {% endif %}
                            {% if object.hashtag.tag.1 %}
                            # {{object.hashtag.tag.1}}
                            {% endif %}
                            {% if object.hashtag.tag.2 %}
                            # {{object.hashtag.tag.2}}
                            {% endif %}
                        </p>
                    </div>
            </div>
        </div>
        {% endfor %}
    </div>
</body>
</html>